import type { Metadata } from "next";
import { cairo } from "./ui/fonts";
import Navbar from "./ui/navbar";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "معهد الدلتا العالي",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${cairo.className} antialiased`}>
        <header className=" relative xl:fixed top-0 w-full z-[100000] bg-light-blue drop-shadow-lg ">
          <Navbar />
        </header>
        <main className="xl:mt-[70px]">{children}</main>
      </body>
    </html>
  );
}
