import type { Metadata, Viewport } from "next";
import { cairo } from "./ui/fonts";
import Navbar from "./ui/root-layout/navbar";
import "./ui/globals.css";
import FooterSection from "./ui/root-layout/footer-section/footer-section";

export const metadata: Metadata = {
  title: "معهد الدلتا العالي",
  description: "Generated by create next app",
  applicationName: "معهد الدلتا العالي",
  manifest: "/manifest.json",
};
export const viewport: Viewport = {
  themeColor: "#f6f6f6",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${cairo.className} antialiased bg-slate-100`}>
        <header className=" h-[70px] flex justify-center items-center relative xl:fixed top-0 w-full z-[100000] bg-light-blue drop-shadow-lg ">
          <Navbar />
        </header>
        <main className="xl:mt-[70px] overflow-y-hidden">{children}</main>
        <FooterSection />
      </body>
    </html>
  );
}
